apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: gitlab-anyuid
  name: gitlab-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-anyuid
subjects:
- kind: ServiceAccount
  name: gitlab-ce-user
