apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: gitlab-ce
  name: gitlab-ce-redis
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: redis:5.0.4-alpine
    generation: 2
    importPolicy: {}
    name: 5.0.4
    referencePolicy:
      type: Source
