apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    name: gitlab-anyuid
  name: gitlab-anyuid
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
